Various fixes and tweaks
* Added "NEW" markers when page is refreshed, using localforage library
to store most recent list of IMDB links as the unique key to check
against.
* Added requirement for postcode for dominos bash script.
* Fixed dominos casperjs script for latest version of dominos website.
* Fixed rentals script to quit early on error getting list from IMDB,
rather than overwriting HTML with an empty list.
* Added "<scripts>" `Message-ID` mail header for failure emails in main
telescuff bash script, for filtering in gmail.
* Added blackboard icon for tv shows page heading (it looks a bit like a
TV).

diff --git a/dominos b/dominos
--- a/dominos
+++ b/dominos
@@ -38,6 +38,11 @@ while true; do
   esac
 done
 
+if [[ $POSTCODE == "" ]]; then
+  echo "Postcode is required (-p/--postcode)"
+  exit 2
+fi
+
 # -- handle non-option arguments
 if [[ $# -ne 0 ]]; then
   echo "$0: unknown additional parameter '$1'"
@@ -57,7 +62,7 @@ if [ "$EMAIL" != "" ]; then
     *) subject="Script Error" ;;
   esac
 
-  echo "$output" | mail -s "Dominos Vouchers - $subject" $EMAIL;
+  echo "$output" | mail -a "Message-ID:<scripts@dave.desktop>"  -s "Dominos Vouchers - $subject" $EMAIL;
 
 else
   $CMD
